# Generated by Django 3.1 on 2020-08-26 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id_int', models.IntegerField(primary_key=True, serialize=False)),
                ('iD_member', models.CharField(max_length=20)),
                ('real_name', models.CharField(max_length=20)),
                ('tz', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Activity_period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('id_int', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='activity', to='round1.user')),
            ],
        ),
    ]
